services:

  mariadb:
    build:
        context: ./requirements/mariadb/
        args:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE} 
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
        - bridge_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    build: ./requirements/wordpress/
    restart: always
    env_file:
      - .env
    environment:
        DB_HOST: mariadb
    volumes:
        - wp_data:/var/www/html
    depends_on:
        mariadb:
          condition: service_healthy
    networks:
        - bridge_net

  nginx:
    build: ./requirements/nginx/
    restart: always
    ports:
        - "8080:80"
    volumes:
        - wp_data:/var/www/html:ro
    depends_on:
        - wordpress
    networks:
        - bridge_net


volumes:
  db_data:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /home/nalebrun/data/db/
  wp_data:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /home/nalebrun/data/wp/

networks:
  bridge_net:
    driver: bridge
